### ISSUE TITLE
error opening a pdf

### ISSUE THREAD

**Issue by TeLLie** [nettstudio/fusepdf#12]
Hello
I compiled it using QT5 v 5.15.2

Since i update it to latest source it wont open a pdf f anymore

Before the update from today it opens a pdf fine, any idea why it failing now?

Using it with OS/2

**Comment by rodlie** [comment]
Hi,

I'm was fixing some warnings and depreciated functions in Qt 5.15 on Windows, might have broken something (main is not always stable).

Could you run the app from a terminal and paste the output (do not build it in release mode), it should show the command used.

**Comment by TeLLie** [comment]
Hi
Thankz for fast reply
I just have the release, and no debug as there is only release under os2


Op vr 25 mrt. 2022 21:47 schreef Ole-André ***@***.***>:

**Comment by rodlie** [comment]
Could you try the `revert` branch? https://github.com/nettstudio/fusepdf/commit/4eef21004df0329e16bc1ee89fee6294e0e5ab90 should fix the issue (in theory).

**Comment by TeLLie** [comment]
Hi

Yes that's working now i can again open a pdf 👍
Thankz ...

Op vr 25 mrt. 2022 22:11 schreef Ole-André ***@***.***>:

**Comment by rodlie** [comment]
Great, I will merge the changes into `main`.
